---
title: Algorithmic, discrete and tropical geometry
description: Workshop on recent developments in algorithmic, discrete and tropical geometry
keywords: algorithms, discerete geometry, tropical geometry, michael joswig

extensions:
  - typography
  - fences
  - embed
  - highlighting
